# Form implementation generated from reading ui file 'gateManager1.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(200, 175, 158);\n"
"color: rgb(170, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(0, 0, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.labelDate = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(120, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.labelTrack = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTrack.setGeometry(QtCore.QRect(120, 130, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelTrack.setFont(font)
        self.labelTrack.setObjectName("labelTrack")
        self.labelRaceNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelRaceNumber.setGeometry(QtCore.QRect(120, 180, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelRaceNumber.setFont(font)
        self.labelRaceNumber.setObjectName("labelRaceNumber")
        self.labelNumberOfHorses = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelNumberOfHorses.setGeometry(QtCore.QRect(120, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelNumberOfHorses.setFont(font)
        self.labelNumberOfHorses.setObjectName("labelNumberOfHorses")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(340, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.dateEdit.setObjectName("dateEdit")
        self.dropdownRacetrack = QtWidgets.QComboBox(parent=self.centralwidget)
        self.dropdownRacetrack.setGeometry(QtCore.QRect(340, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dropdownRacetrack.setFont(font)
        self.dropdownRacetrack.setStyleSheet("background-color: rgb(255, 255, 255);border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   \n"
"")
        self.dropdownRacetrack.setObjectName("dropdownRacetrack")
        self.inputRaceNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputRaceNumber.setGeometry(QtCore.QRect(340, 180, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.inputRaceNumber.setFont(font)
        self.inputRaceNumber.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   \n"
"")
        self.inputRaceNumber.setObjectName("inputRaceNumber")
        self.dropdownNumberOfHorses = QtWidgets.QComboBox(parent=self.centralwidget)
        self.dropdownNumberOfHorses.setGeometry(QtCore.QRect(340, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dropdownNumberOfHorses.setFont(font)
        self.dropdownNumberOfHorses.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.dropdownNumberOfHorses.setObjectName("dropdownNumberOfHorses")
        self.btnLoadingGate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoadingGate.setGeometry(QtCore.QRect(170, 320, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnLoadingGate.setFont(font)
        self.btnLoadingGate.setStyleSheet("border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.btnLoadingGate.setObjectName("btnLoadingGate")
        self.btnRaceOff = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRaceOff.setGeometry(QtCore.QRect(170, 400, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnRaceOff.setFont(font)
        self.btnRaceOff.setStyleSheet("border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.btnRaceOff.setObjectName("btnRaceOff")
        self.labelMessage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(10, 480, 581, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelMessage.setFont(font)
        self.labelMessage.setStyleSheet("/*background-color: rgb(200, 175, 158);*/\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 0, 0);\n"
"border: 2px solid rgb(170, 0, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.labelMessage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gate Manager"))
        self.labelTitle.setText(_translate("MainWindow", "Gate Manager"))
        self.labelDate.setText(_translate("MainWindow", "Date"))
        self.labelTrack.setText(_translate("MainWindow", "Track"))
        self.labelRaceNumber.setText(_translate("MainWindow", "Race No."))
        self.labelNumberOfHorses.setText(_translate("MainWindow", "Number of Horses"))
        self.btnLoadingGate.setText(_translate("MainWindow", "Entering Starting Gate"))
        self.btnRaceOff.setText(_translate("MainWindow", "Race Off"))
        self.labelMessage.setText(_translate("MainWindow", "Welcome to the Gate Manager"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
